
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/home/thomazllr/.local/share/JetBrains/Toolbox/apps/clion/bin/cmake/linux/x64/share/cmake-3.28/Modules/CMakeDetermineSystem.cmake:233 (message)"
      - "CMakeLists.txt:2 (project)"
    message: |
      The system is: Linux - 6.8.0-35-generic - x86_64
